### ISSUE TITLE
CloudWatcher Failing To Start

### ISSUE THREAD

**Issue by CycleMark** [aws-robotics/cloudwatchlogs-ros1#1]
Hi,

I've been testing cloudwatcher. I updated the sample_configuration.yaml to a custom log_stream_name

However I get the error messages below:

> [ERROR] [1543682968.675952432]: [AWSClient] HTTP response code: 400
> Exception name: ResourceAlreadyExistsException
> Error message: The specified log group already exists
> 5 response headers:
> connection : close
> content-length : 94
> content-type : application/x-amz-json-1.1
> date : Sat, 01 Dec 2018 16:49:28 GMT
> x-amzn-requestid : 116c39c3-f589-11e8-be76-d3e7ff879f8f
> [ERROR] [1543682968.676457696]: [CreateLogGroup] Failed to create Log Group :robot_application_name due to: The specified log group already exists, with error code: 135
> [ERROR] [1543682968.790863450]: [AWSClient] HTTP response code: 400
> Exception name: ResourceAlreadyExistsException
> Error message: The specified log stream already exists
> 5 response headers:
> connection : close
> content-length : 95
> content-type : application/x-amz-json-1.1
> date : Sat, 01 Dec 2018 16:49:27 GMT
> x-amzn-requestid : 117c8dd5-f589-11e8-bd16-65b3e1494de1
> [ERROR] [1543682968.791192148]: [CreateLogStream] Failed to create Log Stream :mxnet_kobuki_robot_log_stream in Log Group :robot_application_name due to: The specified log stream already exists, with error code: 135
> 

According to the config file - it will try to create the log stream if it doesn't exist. Although the error messages seem to indicate otherwise.

How can I resolve this? And where should I expect the log stream to appear - I'm assuming eu-west-2 (I updated this config to reflect this.

Thanks and Regards

Mark

**Comment by mm318** [comment]
Hi Mark,

The error messages seem to indicate that the log stream already exists, rather than they don't exist.

Can you confirm that you don't already see in your CloudWatch Logs the Log Group "robot_application_name" and under it the Log Stream "device_name"?

Thanks

**Comment by mm318** [comment]
My gut feeling here is that these error messages being printed are falsely indicating that there's an error.

**Comment by CycleMark** [comment]
Hi mm318,

Yes agreed that looks like it's the case. I left it up running and sent in a few messages to existing and new log groups and saw the messages come up.

Will close 

Cheers

Mark

**Comment by mm318** [comment]
We will fix these false error messages. Thank you!

**Comment by yyu** [comment]
https://github.com/aws-robotics/cloudwatch-common/pull/1 has been merged

resolving
