### ISSUE TITLE
Possible to send logs by Node 

### ISSUE THREAD

**Issue by CycleMark** [aws-robotics/cloudwatchlogs-ros1#14]
Hi,

Quick question - is it possible to send logs by node and/or instead of topic?

Thanks

Mark

**Comment by xabxx** [comment]
Hi Mark @CycleMark ,

For the current implementation, the `cloudwatch_logger` node subscribes to the `rosout_agg` topic to get logs. As long as all the logs you'd like to send to AWS CloudWatch Logs get published to the `rosout` topic (which the `rosout_agg` topic subscribes to), it doesn't matter how you send logs.

Please let me know if this makes sense.

Thanks,
Abby

**Comment by CycleMark** [comment]
Hi Abby,

Thanks - yep I have is working that way then filtering on the CloudWatch side. Just looking at pre-filtering options.

Cheers 

Mark

**Comment by xabxx** [comment]
Hey Mark @CycleMark ,

If you would like to filter out logs by node name, checkout line 47 in [this source file](https://github.com/aws-robotics/cloudwatchlogs-ros1/blob/master/cloudwatch_logger/src/log_node.cpp). 

We plan to implement the feature you described in the future, for now, I hope this will be one of your options for pre-filtering out logs.

Thanks!
Abby

**Comment by CycleMark** [comment]
Hi Abby,

That's great - thanks, I'll gave a play with this.

Cheers

Mark

**Comment by CycleMark** [comment]
@xabxx - many thanks - worked a treat. Much less noise in the logs

Mark

**Comment by xabxx** [comment]
@CycleMark glad to hear :) 👍
