### ISSUE TITLE
Ensure Log Batch Doesn't Span More Than 24 Hours

### ISSUE THREAD

**Issue by connoranderson** [aws-robotics/cloudwatchlogs-ros1#54]
I've noticed that occasionally the cloudwatch node crashes when it tries to batch old logs spanning 24 hour time spans. We should handle this more gracefully and output an error to the user about which logs got dropped from the batch.

```
[ERROR] [1576699115.494884036]: [AWSClient] HTTP response code: 400
Exception name: InvalidParameterException
Error message: The batch of log events in a single PutLogEvents request cannot span more than 24 hours.
5 response headers:
connection : close
content-length : 139
content-type : application/x-amz-json-1.1
date : Wed, 18 Dec 2019 19:58:35 GMT
x-amzn-requestid : {omitted}

[ERROR] [1576699115.496820436]: [SendLogsRequest] Send log request failed due to: The batch of log events in a single PutLogEvents request cannot span more than 24 hours., with error code: 131

[ERROR] [1576699115.496979688]: [SendLogsToCloudWatch] Failed to send to CloudWatch in Log Group: robot_app Log Stream: {omitted} with error code: 1
[cloudwatch_logger-18] process has died [pid 22428, exit code -11, cmd /catkin_ws/devel/lib/cloudwatch_logger/cloudwatch_logger __name:=cloudwatch_logger __log:=/root/.ros/log/b7895c34-21d0-11ea-a9e1-d0c5d3afb37d/cloudwatch_logger-18.log].
log file: /root/.ros/log/b7895c34-21d0-11ea-a9e1-d0c5d3afb37d/cloudwatch_logger-18*.log
```

**Comment by connoranderson** [comment]
After investigating a little more, my cloudwatch node was loading previous messages from 

```
[restoreFromDisk] Loading existing token store from: /root/.ros/cwlogs/token_store.info
```

Is it possible that I had a cached message over 24 hours old which caused this repeat issue?

**Comment by xabxx** [comment]
Hi there. I am investigating this issue and will respond as soon as I make new discoveries. Thanks!

**Comment by xabxx** [comment]
Hey there. I tried to repro this issue and was not able to see the same error that you ran into. the crash you experienced perhaps was not related to old logs being cached. Is it possible to share your log file with me?

**Comment by xabxx** [comment]
@connoranderson hi. could you follow [readme](https://github.com/aws-robotics/cloudwatch-common/blob/master/README.md) in this repo and try to build this [PR](https://github.com/aws-robotics/cloudwatch-common/pull/46), and use it please? 

This fix may help you with your issue, but I still would like to take a look at your log files to be sure.

Thanks and please keep me posted!

**Comment by connoranderson** [comment]
Unfortunately I deleted the offending token_store.info file during my initial troubleshooting and didn’t back it up so I don’t have it anymore. If I can figure out how to better repro the issue I will definitely build this latest PR for testing to confirm it handles the issue!

**Comment by connoranderson** [comment]
Confirmed the log is no longer on my machine. I'll go ahead and close this and re-open if I am able to reproduce after your fix is merged.
