### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by CycleMark** [aws-robotics/cloudwatchlogs-ros1#55]
Hi,

I'm had this build before - those about a year back. Just refreshing and rebuilding now I'm running into this error:

/opt/ros/kinetic/include/aws_ros1_common/sdk_utils/ros1_node_parameter_reader.h:34:12: error: ‘Aws::AwsError Aws::Client::Ros1NodeParameterReader::ReadMap(const char*, std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&) const’ marked ‘override’, but does not override
   AwsError ReadMap(const char * name, std::map<std::string, std::string> & out)

Any idea what this cause is?

Thanks

Mark

**Comment by xabxx** [comment]
hi, may I ask you which commands you ran to get the artifact and its dependencies?

**Comment by CycleMark** [comment]
Hi - just following the instructions - https://github.com/aws-robotics/cloudwatchlogs-ros1.

Seems to all work okay.

I've also tried locally fetching cloudwatch-common    monitoringmessages-ros1  utils-ros1
cloudwatchlogs-ros1  utils-common into the sec. Same result

Thanks

Mark

**Comment by mm318** [comment]
Hi Mark,

The error you're running into definitely shows that you have an order version of `ros1_node_parameter_reader.h`.

Can you make sure that you don't have any apt packages like `ros-${ROS_DISTRO}-aws-common` or `ros-${ROS_DISTRO}-aws-ros1-common` installed on your system? And if you've locally fetched the package sources from GitHub, make sure they're either all on the `master` branch or all on the `release` branch.

Thanks

**Comment by CycleMark** [comment]
Hi - cool thanks that fixed it. Looks like I wasn't pulling the HEAD of the master branch and also, like you say, I had some old version in the distro. Now all build from src and working :)

Cheers

Mark
