### ISSUE TITLE
Feature Flag to turn off topic listing for a node

### ISSUE THREAD

**Issue by mr337** [aws-robotics/cloudwatchlogs-ros1#57]
For some nodes that are subscribed to a lot of topic can cause a log message to be filled with a lot of unnecessary information.
```
158.352000000 INFO [node name: /cloud] [topics: /waypoint/parameter_updates, /rosout, /waypoint/parameter_descriptions, /cloud/parameter_updates, /steering/pid/parameter_descriptions, /autopilot/parameter_descriptions, /lidar/parameter_descriptions, /vel, /steering/pid/parameter_updates, /safety_halt, /waypoint, /autosteer/parameter_descriptions, /cloud/parameter_descriptions, /hal/parameter_descriptions, /autosteer/parameter_updates, /clock, /autopilot/parameter_updates, /lidar/parameter_updates, /hal/parameter_updates] Valid Config
```

Would it be possible to have a flag to turn the `[topics: ...]` information off? Would help to clean up the logs and reduce cellular bandwidth.

**Comment by xabxx** [comment]
Hi there. If I understand you correctly, you are asking if you could filter out some of the logging information published by some nodes. If that's the case, what you could do is add the node names that you do no wish its logs published to CloudWatch logs in this file https://github.com/aws-robotics/cloudwatchlogs-ros1/blob/214fc7768bf784b059b9c1c9688575adf4cbfaf5/cloudwatch_logger/config/sample_configuration.yaml#L28.

Please let me know if you have any more questions!

**Comment by mr337** [comment]
Hi xabxx, that is close but not quite.

On each log entry there are two fields
`[node name: /cloud] [topics: ...`

We do not need the information of `topics` to be sent. We only need the `node name` so we can identify which node generated the log. The `topics` is unneeded information for our application as we have descriptive node names.

I would guess that for some this would be useful if there are two `lidar` nodes and need to identify which node is which and that information could be useful. For our application is is just extra bandwidth we are looking to trim.

Happy to expand further or share extra examples :)

**Comment by raghaprasad** [comment]
Hi @mr337, 
We have added a new feature to disable topics from appearing in the log messages. 
Please try the master branch to access the feature. 
We will be bloom releasing these changes shortly.

**Comment by mr337** [comment]
Thank for the quick turn around. Happy to try and report back any issues!
