### ISSUE TITLE
Integration with CloudWatch Insights

### ISSUE THREAD

**Issue by CycleMark** [aws-robotics/cloudwatchlogs-ros1#7]
Hi,

I've had the CloudWatch logger working well now for a few weeks.

Just looking at what I can do to integrate with Insights.

At the moment my Robots' nodes publish messages using ROS_INFO("blah blah blah");

One of the messages it publishes is:

"Redocking Attempts: 0" 

Which is a simple String with an integer, basically indicating if the robot has had problems docking.

What I'd like to use Insights for is to add a filter to my selection such that if the redocking attempts are > 0 I get and alert.

Current Filter Looks Like:

fields @timestamp, @message
| filter @message like /Redocking Attempts/
| sort @timestamp desc
| limit 20

Any ideas re: how I could achieve this? Will I have to create a JSON message instead (Is there a JSON message API readily available?)

Thanks & Regards

Mark

**Comment by ryanewel** [comment]
Hi Mark,

You can add a line to your query like:
| parse 'Redocking Attempts: *' as @attempts
You can then get statistics on the variable "@attempts". 

According to this [article](https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-logs-insights-fast-interactive-log-analytics/) (at the very bottom) you may have to write a bit of code to get these results into CloudWatch Metrics.

Another possibility would be to use the [AWS CloudWatch Metrics node](https://github.com/aws-robotics/cloudwatchmetrics-ros1) which would allow you to publish directly to CloudWatch metrics and set up alarms there.

A third option would be to use a [Metric Filter](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html) which would allow you to extract the integer field and publish it to a metric (scroll down to the section on "Using Metric Filters to Extract Values from Space-Delimited Log Events")

Hope this helps!

**Comment by CycleMark** [comment]
Hi @ryanewel 

Many thanks for these. It's pretty much perfect:

fields @timestamp, @message
| filter @message like /Redocking Attempts/
| parse 'Redocking Attempts: *' as @attempts
| filter attempts = 0
| sort @timestamp desc
| limit 20

I'm able to see @attempts come up as a variable and indeed it's parsed and displayed in the results table. But with:

| filter attempts = 0

Then it doesn't display anything (all docking attempts are zero). I've played with other forms that I thought might work but get the same result e.g

| filter attempts like  /0/

What am i missing here?

Thanks Mark

**Comment by ryanewel** [comment]
It looks like you may be missing the @ in front of @attempts. Then either of your queries should work (although be careful with the 2nd, it'll match anything that contains a 0). 

You don't need the @ to mark a variable so you could also just rename it "attempts"

**Comment by CycleMark** [comment]
Yeah agreed re: 2nd - just one of a few different attempts.

I've attached a couple of screen shots - same data set, though no data output with the filter included

![couldwatchmetrics-additionalfilter](https://user-images.githubusercontent.com/27418725/51269920-8c018780-19bb-11e9-93df-98e7e5d3118c.PNG)
![couldwatchmetrics-noadditionalfilter](https://user-images.githubusercontent.com/27418725/51269924-902da500-19bb-11e9-8edb-0d9641b5d32e.PNG)

**Comment by ryanewel** [comment]
I tried creating a log group and populating it with events like yours. Your first query returned the expected events, so I'm not sure exactly what's going on here.

Since this isn't an issue with the cloudwatch_logger node I'm going to close this issue and I'd recommend making a post on the [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=138&start=0).

If you run into any other issues with the node or there's a feature you'd like to see added please feel free to open another issue.

**Comment by CycleMark** [comment]
No worries - many thanks anyway
